apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lic-portal.fullname" . }}
  labels:
    {{- include "lic-portal.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  APP_URL: {{ .Values.config.APP_URL | quote }}
  PORT: {{ .Values.config.PORT | quote }}

  NEXT_PUBLIC_PRODUCT_CODE: {{ .Values.config.NEXT_PUBLIC_PRODUCT_CODE | quote }}
  NEXT_PUBLIC_PRODUCT_NAME: {{ .Values.config.NEXT_PUBLIC_PRODUCT_NAME | quote }}
  NEXT_PUBLIC_PRODUCT_SUFFIX: {{ .Values.config.NEXT_PUBLIC_PRODUCT_SUFFIX | quote }}

  DATABASE_POOL_SIZE: {{ .Values.config.DATABASE_POOL_SIZE | quote }}

  AUTH_TRUST_HOST: {{ .Values.config.AUTH_TRUST_HOST | quote }}

  SMTP_HOST: {{ .Values.config.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.config.SMTP_PORT | quote }}
  SMTP_USER: {{ .Values.config.SMTP_USER | quote }}
  SMTP_FROM: {{ .Values.config.SMTP_FROM | quote }}
  SMTP_SECURE: {{ .Values.config.SMTP_SECURE | quote }}

  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  DEFAULT_LOCALE: {{ .Values.config.DEFAULT_LOCALE | quote }}

  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.OTEL_SERVICE_NAME | quote }}