{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lic-portal.fullname" . }}
  labels:
    {{- include "lic-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  AUTH_SECRET: {{ .Values.secret.AUTH_SECRET | quote }}
  APP_MASTER_KEY: {{ .Values.secret.APP_MASTER_KEY | quote }}
  SMTP_PASSWORD: {{ .Values.secret.SMTP_PASSWORD | quote }}

  INITIAL_ADMIN_EMAIL: {{ .Values.secret.INITIAL_ADMIN_EMAIL | quote }}
  INITIAL_ADMIN_PASSWORD: {{ .Values.secret.INITIAL_ADMIN_PASSWORD | quote }}
  INITIAL_ADMIN_MATRICULE: {{ .Values.secret.INITIAL_ADMIN_MATRICULE | quote }}
{{- end }}