global:
  registry: "harbor-factory.s2m.ma/portal-inprogress"
  imagePullSecrets:
    - name: lic-portal-image-puller

replicaCount: 2

image:
  repository: s2m-lic
  pullPolicy: Always
  tag: "develop"

nameOverride: ""
fullnameOverride: ""

containerPort: 3000

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

config:
  NODE_ENV: "production"
  APP_URL: "https://lic-portal-integration.app.dev.s2m.ma"
  PORT: "3000"

  NEXT_PUBLIC_PRODUCT_CODE: "LIC"
  NEXT_PUBLIC_PRODUCT_NAME: "Licence Manager"
  NEXT_PUBLIC_PRODUCT_SUFFIX: "PORTAL"

  DATABASE_POOL_SIZE: "10"

  AUTH_TRUST_HOST: "true"

  SMTP_HOST: "smtp.s2m.ma"
  SMTP_PORT: "587"
  SMTP_USER: "noreply@s2m.ma"
  SMTP_FROM: "Licence Manager <noreply@s2m.ma>"
  SMTP_SECURE: "false"

  LOG_LEVEL: "info"
  DEFAULT_LOCALE: "fr"

  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "s2m-lic"

secret:
  create: true
  existingSecret: ""

  DATABASE_URL: "postgresql://lic_portal:CHANGE_ME@postgresql.integration.svc.cluster.local:5432/lic_portal"
  AUTH_SECRET: "CHANGE_ME_MINIMUM_32_CHARACTERS_AUTH_SECRET"
  APP_MASTER_KEY: "CHANGE_ME_MINIMUM_32_CHARACTERS_MASTER_KEY"
  SMTP_PASSWORD: "CHANGE_ME_SMTP_PASSWORD"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: lic-portal-integration.app.dev.s2m.ma
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # tls:
  #   - secretName: lic-portal-tls
  #     hosts:
  #       - lic-portal-integration.app.dev.s2m.ma

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /api/health/ready
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6
  successThreshold: 1

livenessProbe:
  enabled: true
  httpGet:
    path: /api/health/live
    port: http
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: true
  httpGet:
    path: /api/health/live
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 12
  successThreshold: 1

nodeSelector: {}

tolerations: []

affinity: {}
migration:
  enabled: true
  backoffLimit: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
